Add unit tests for Link
aowss/open-api pull request #24
Opened 2021-06-06 12:47 UTC by amit1307

### Summary of change
This PR is for adding parser tests for Link model object. The Link specification can be found here: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#linkObject

### Related issue
This PR closes https://github.com/aowss/open-api/issues/9

2021-06-06 15:30 UTC, aowss requested changes
Thanks for your help.

2021-06-06 15:30 UTC, aowss commented on model/src/main/java/openapi/model/v310/Link.java
>  //  TODO: should operationRef be a URI ?
you can remove that

2021-06-06 15:30 UTC, aowss commented on model/src/main/java/openapi/model/v310/Link.java
> + *                     This field is mutually exclusive of the {@code operationId} field, and MUST point to an {@link Operation} Object. Relative {@code operationRef} values MAY be used to locate an
thanks for removing the package name.
could you do that to the 2 other files that have a fully qualified name. server variable and tag.

2021-06-06 15:30 UTC, aowss commented on model/src/main/java/openapi/model/v310/Link.java
> + * @param requestBody  A literal value or {expression} to use as a request body when calling the target operation.
good catch

2021-06-06 15:30 UTC, aowss commented on model/src/main/java/openapi/model/v310/Link.java
> +public record Link(URL operationRef, String operationId, Map<String, String> parameters, Object requestBody, String description, Server server) {
why URL? isn't that supposed to be URI?

2021-06-06 15:30 UTC, aowss commented on model/src/main/java/openapi/model/v310/Link.java
> +            throw new IllegalArgumentException("An 'link' Object can't have both an 'operationRef' and an 'operationId' field");
```suggestion
            throw new IllegalArgumentException("A 'link' Object can't have both an 'operationRef' and an 'operationId' field");
```

2021-06-06 15:30 UTC, aowss commented on model/src/main/java/openapi/model/v310/Link.java
> +    private boolean isNullOrEmpty(String str) {
i would inline that check and remove that method

2021-06-06 15:30 UTC, aowss commented on model/src/main/java/openapi/model/v310/Link.java
>      public Link {
I thought you were going to create 2 alternate constructors ( similar to License )

```
public Link(@NotNull URL operationRef, Map<String, String> parameters, Object requestBody, String description, Server server) { ... }
```
and
```
public Link(@NotNull String operationId, Map<String, String> parameters, Object requestBody, String description, Server server) { ... }
```

2021-06-06 15:30 UTC, aowss commented on model/src/main/java/openapi/model/v310/Link.java
> +    }
I think it would be good to add the validation around the key of the `parameters` map as explained [in the spec](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#runtime-expressions)

2021-06-06 15:30 UTC, aowss commented on parser/src/test/resources/Link/all-fields-operation-id.json
> +{
I think there is no link in the [full example](https://github.com/aowss/open-api/tree/main/parser/src/test/resources/Full). it would probably be good to add one

2021-06-06 15:30 UTC, aowss commented on parser/src/test/resources/Link/all-fields-operation-id.json
> +  "server": {
You can use a simple server element.
The tests around server have already been done in server so there is no need to make this one complex, i.e. no need for variables.

2021-06-06 15:30 UTC, aowss commented on parser/src/test/java/openapi/model/v310/LinkTest.java
> +    static String missingOperationIdentifier = "/Link/missing-operation-identifier.json";
You are missing a test case where both are specified.

2021-06-06 15:30 UTC, aowss commented on parser/src/test/java/openapi/model/v310/LinkTest.java
> +    @Test
In the other test classes, the YAML follows the corresponding JSON to i would put this one before the one above

2021-06-06 15:30 UTC, aowss commented on parser/src/test/java/openapi/model/v310/LinkTest.java
> +        assertThat(link.server().description(), is("The production API server"));
No need to do the other server tests. this has been validated in the server class.
so as long as we get one server item, like url, we can stop.

2021-06-08 17:26 UTC, amit1307 commented on model/src/main/java/openapi/model/v310/Link.java
> + *                     This field is mutually exclusive of the {@code operationId} field, and MUST point to an {@link Operation} Object. Relative {@code operationRef} values MAY be used to locate an
sure, done.

2021-06-08 17:26 UTC, amit1307 commented on model/src/main/java/openapi/model/v310/Link.java
> +public record Link(URL operationRef, String operationId, Map<String, String> parameters, Object requestBody, String description, Server server) {
yes right, changed it now.

2021-06-08 17:30 UTC, amit1307 commented on model/src/main/java/openapi/model/v310/Link.java
>      public Link {
yes but the problem with that is we would still be able to create a `Link` object with both `operationRef` and `operationId` null due to the default record constructor?

2021-06-08 17:55 UTC, amit1307 commented on parser/src/test/java/openapi/model/v310/LinkTest.java
> +        assertThat(link.server().description(), is("The production API server"));
Actually they were not tested in server tests but have moved these assertions in the server tests.

2021-06-08 17:56 UTC, aowss commented on model/src/main/java/openapi/model/v310/Link.java
>      public Link {
that's not a problem and we can't really work around that but at runtime it will fail

2021-06-08 17:58 UTC, amit1307 commented on parser/src/test/resources/Link/all-fields-operation-id.json
> +  "server": {
Just tried that since we have a few validations for `Server` object so it fails to create server object without all the fields.

2021-06-08 17:59 UTC, amit1307 commented on model/src/main/java/openapi/model/v310/Link.java
> +    }
Didn't understand the validations from the spec, lets catch up offline about this bit.

2021-06-08 18:19 UTC, amit1307 commented on model/src/main/java/openapi/model/v310/Link.java
>      public Link {
done.

2021-06-08 19:56 UTC, aowss commented on parser/src/test/resources/Link/all-fields-operation-id.json
> +  "server": {
that is strange. this should be able to create a server without variables

2021-06-08 20:04 UTC, aowss commented on model/src/main/java/openapi/model/v310/Link.java
> +    }
- If the key contains a `.`, then the first part should be one of the valid locations https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#parameterIn
- The value should be a constant or an expression. An expression starts with `$` and needs to conform to what is defined in the link above. So for example, it should be one of : `$url" / "$method" / "$statusCode" / "$request." source / "$response." source`

2021-06-12 16:42 UTC, aowss requested changes

2021-06-12 16:42 UTC, aowss commented on model/src/main/java/openapi/model/v310/Link.java
> +            throw new IllegalArgumentException("A 'link' Object can't have both an 'operationRef' and an 'operationId' field");
Why did you add a new line ? in the rest of the code base there is no new line.
If we add a new line here, we need to do the same in the rest of the code base

2021-06-12 16:42 UTC, aowss commented on model/src/main/java/openapi/model/v310/Link.java
> +     * Creates an instance of a {@code Link} record class where the link will be resolved using operationRef value to locate an existing Operation Object.
```suggestion
     * Creates an instance of a {@code Link} record class where the link will be resolved using the {@code operationRef} value to locate an existing {@link Operation} Object.
```

2021-06-12 16:42 UTC, aowss commented on model/src/main/java/openapi/model/v310/Link.java
> +     * Creates an instance of a {@code Link} record class where the link will be resolved using operationRef value to locate an existing Operation Object.
This is not true. This one is with oprationId

2021-06-12 16:42 UTC, aowss commented on model/src/main/java/openapi/model/v310/Link.java
> +    }
I am not sure this was done.
Maybe we can just add a TODO for that

2021-06-12 16:42 UTC, aowss commented on model/src/main/java/openapi/model/v310/OpenApi.java
> +public record OpenApi(@NotNull Version openapi, @NotNull Info info, URI jsonSchemaDialect, List<Server> servers, Map<String, PathItem> paths, Map<String, PathItem> webhooks, Components components, Li
I am not sure why you added a Link here.
The spec doesn't say that : See https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#openapi-object

2021-06-12 16:42 UTC, aowss commented on parser/src/test/resources/Full/all-fields.json
> +  "link": {
again i don't think this is valid according to the spec

2021-06-12 16:42 UTC, aowss commented on parser/src/test/resources/Full/all-fields.yaml
> +link:
same as above

2021-06-12 16:42 UTC, aowss commented on parser/src/test/resources/Link/both-operation-identifier-provided.json
> +{
In the other test cases, this file is called something like `operationId-operationRef`
If we want to change the naming to this naming, we need to do it for all these files

2021-06-12 16:42 UTC, aowss commented on parser/src/test/resources/Link/both-operation-identifier-provided.json
> +  "parameters": {
This file should only contain the 2 fields that are mutually exclusive and the mandatory parameters

2021-06-12 16:42 UTC, aowss commented on parser/src/test/resources/Link/missing-operation-identifier.json
> +{
This file is generally called `missing-fields`. If we want to rename, then we need to do it all over.

2021-06-12 16:42 UTC, aowss commented on parser/src/test/java/openapi/model/v310/LinkTest.java
> +    @DisplayName("All fields with operation ref [YAML]")
```suggestion
    @DisplayName("All fields with operation id [YAML]")
```

2021-06-12 16:42 UTC, aowss commented on parser/src/test/java/openapi/model/v310/LinkTest.java
> +
why are there 2 new lines ?

2021-06-12 16:42 UTC, aowss commented on parser/src/test/java/openapi/model/v310/LinkTest.java
> +}
There should be a new line before the last `}`

2021-06-12 16:42 UTC, aowss commented on parser/src/test/resources/Link/all-fields-operation-id.json
> +  "server": {
Since you added the variables test to the server, we should use a simple server here without variables. If this doesn't work, it means we have an issue that needs to be addressed as a bug for Server

2021-06-12 16:42 UTC, aowss commented on parser/src/test/resources/Link/all-fields-operation-id.yaml
> +  variables:
same as above

2021-06-12 16:42 UTC, aowss commented on parser/src/test/resources/Link/all-fields-operation-ref.json
> +    "variables": {
same as above

2021-06-12 16:42 UTC, aowss commented on parser/src/test/resources/Link/all-fields-operation-ref.yaml
> +  variables:
same as above

2021-06-12 21:34 UTC, amit1307 commented on model/src/main/java/openapi/model/v310/Link.java
> +            throw new IllegalArgumentException("A 'link' Object can't have both an 'operationRef' and an 'operationId' field");
Have changed it now. Personally I like if with curly braces even if there is just one line but I guess not a big deal.

2021-06-12 21:51 UTC, amit1307 commented on parser/src/test/resources/Link/all-fields-operation-id.yaml
> +  variables:
I am bit confused why do you expect a `Server` object can be constructed without variable. I can see below validation (and some more) in `Server` class:

`if (variables == null || variables.isEmpty()) throw new IllegalArgumentException("The 'url' field can't use variable substitutions if the 'variables' field is not present");`

2021-06-12 22:40 UTC, amit1307 commented on model/src/main/java/openapi/model/v310/OpenApi.java
> +public record OpenApi(@NotNull Version openapi, @NotNull Info info, URI jsonSchemaDialect, List<Server> servers, Map<String, PathItem> paths, Map<String, PathItem> webhooks, Components components, Li
Yeah that was a mistake, have just reverted it and will add it soon at the correct place.

2021-06-23 13:23 UTC, aowss commented on parser/src/test/resources/Link/all-fields-operation-id.yaml
> +  variables:
the mandatory fields example ( `mandatory-fields.json` ) is

```json
{
  "url": "https://development.gigantic-server.com/v1"
}
```

2021-06-23 13:37 UTC, merged